### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by smukkejohan** [antfu/vscode-iconify#56] opened 2023-08-24 16:49 UTC
### Describe the bug

Plugin stopped working recently, for my corworker that I recommended it too it stopped working as well.

### Reproduction

Following the readme we setup unplugin-icons with sveltekit and had this plugin working to give previews. Now it stopped working we did not change any configuration in regards to unplugin-icons config, and plugin is installed and not reporting any errors.

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 840.11 MB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 19.0.0 - ~/.asdf/installs/nodejs/19.0.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 116.0.5845.110
    Edge: 116.0.1938.54
    Firefox: 116.0.3
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-08-26 11:24
It's working fine to me, I'd need a reproduction. 

---

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-26 11:24 UTC

**Comment by julien-blanchon** [comment] 2023-11-08 18:27
I can confirm that something is wrong even when rolling back to previous version the intellisense is not working (but the icon preview is working). The console show nothing special expect icon download

**Comment by julien-blanchon** [comment] 2023-11-08 18:28
Thw windows console show that: 
<img width="1104" alt="Screenshot 2023-11-08 at 19 28 15" src="https://github.com/antfu/vscode-iconify/assets/11278197/7c087bea-0e4f-42af-bde5-cf2e389bab0e">

**Comment by smukkejohan** [comment] 2023-11-09 10:10
Didn't manage to find a way to reproduce, but it did start working again after a recent update.

**Comment by julien-blanchon** [comment] 2023-12-28 21:55
Maybe this is the CDN: https://cdn.jsdelivr.net/gh/iconify/icon-sets/json
It return an error: Package size exceeded the configured limit of 50 MB. Try https://github.com/iconify/icon-sets/tree/2.2.162/json instead.
