### ISSUE TITLE
Intellisense doesn't work.

### ISSUE THREAD

**Issue by wallysonn** [antfu/vscode-iconify#53] opened 2023-08-01 17:56 UTC
### Describe the bug

I can see the icon inside the attribute, but the intellisense doesn't work. Any idea? I'm using a Nuxt 3 project with NuxtLab UI.
`<UButton icon="i-heroicons-magnifying-glass" />`

My file settings.json is empty during test.

### Reproduction

local

### System Info

```Shell
System:
    OS: macOS 12.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 302.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-08-01 19:38
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-01 19:38 UTC

**Comment by craigerskine** [comment] 2023-08-07 16:46
I'm having the same issue... If I rollback to v0.5.4 then the intellisense typeahead works again.

**To reproduce:**

- In a compatible file/attribute type a prefix and then `:` - this normally triggers the typeahead for that particular iconset.

In v0.6.0 and 0.6.1 nothing happens. However, if you happen to type a valid icon name it does render.

***

v0.6.0 & 0.6.1
![v061](https://github.com/antfu/vscode-iconify/assets/56437/56abf069-df97-4a53-b330-142a50b369fd)

v0.5.4
![v054](https://github.com/antfu/vscode-iconify/assets/56437/cde5ae1c-7a40-432b-9965-cb6570c5c5b6)

**Comment by julien-blanchon** [comment] 2023-11-08 18:20
+1
