### ISSUE TITLE
IntelliSense autocomplete doesn't work with any version

### ISSUE THREAD

**Issue by julien-blanchon** [antfu/vscode-iconify#72] opened 2024-03-11 16:48 UTC
### Describe the bug

VScode-iconify IntelliSense isn't working for a while on both my computer. When I try to target autocompletion for a Svelte `<Icon icon="mdi:loading" class="mr-2 h-4 w-4 animate-spin" />` in `mdi:loading`. I don't get any error in the extension tab but I get the following error the vscode js console debugger:
<img width="545" alt="Screenshot 2024-03-11 at 17 47 27" src="https://github.com/antfu/vscode-iconify/assets/11278197/d2dc799a-a876-4df7-8b6a-6279d034f329">

### Reproduction

Reproduction

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 69.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 4.0.1 - ~/.volta/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.4 - ~/.local/share/pnpm/pnpm
    bun: 1.0.30 - /opt/homebrew/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by isimmons** [comment] 2024-11-07 06:22
I get no autocomplete but preview works. I tried mdi and twemoji sets. I am in an astro project using the Icon component.

```js
<Icon
   name="mdi:account"
   size="48"
/>
```

**Comment by antfu** [comment] 2024-11-16 08:51
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-11-16 08:51 UTC
