### ISSUE TITLE
Display white icons on dark theme

### ISSUE THREAD

**Issue by shrekuu** [antfu/vscode-iconify#73] opened 2024-04-03 03:44 UTC
### Clear and concise description of the problem

<img width="271" alt="image" src="https://github.com/antfu/vscode-iconify/assets/3136026/a36fb1a1-782f-410d-85e0-a6b340371e33">

If I use a dark theme. The icon is not enough. 

### Suggested solution

Make it white on dark theme would be great.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by maxmarchuk** [comment] 2024-04-15 23:34
This already works, you may just need to restart the IDE
![image](https://github.com/antfu/vscode-iconify/assets/2680236/a86e9e50-d58f-42b2-a101-97e80bcc731a)

**Comment by antfu** [comment] 2024-04-15 23:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-15 23:42 UTC
Labels: enhancement
