### ISSUE TITLE
Icons are not shown in the editor

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [antfu/vscode-iconify#17] opened 2022-02-11 10:39 UTC
The current versions of vscode stable/insiders does not seem to work.
`q-icon(name="mdi-magnify")`
mdi json is downloaded but is not shown in a vue sfc pug template

**Comment by antfu** [comment] 2023-08-01 12:01
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-01 12:01 UTC
